# Generated by Django 4.0.3 on 2022-04-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Type', models.CharField(max_length=120)),
                ('Introduction', models.TextField()),
            ],
        ),
    ]
