# Generated by Django 4.0.3 on 2022-04-06 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speculum_mundi_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='Introduction',
            new_name='introduction',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='Type',
            new_name='summarytype',
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('timestamp', models.CharField(max_length=120)),
                ('thread', models.TextField()),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=120)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speculum_mundi_data.summary')),
            ],
        ),
    ]
