# Generated by Django 4.0.3 on 2022-04-07 05:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('speculum_mundi_data', '0002_rename_introduction_summary_introduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AbstractToTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for abstract-timeline relationship', primary_key=True, serialize=False)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speculum_mundi_data.abstract')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('terrain', models.TextField()),
                ('climate', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for opinion in a discussion', primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=120)),
                ('timestamp', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('sources', models.URLField(max_length=120)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for timeline object', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('time', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speculum_mundi_data.abstract')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineToAbstract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for timeline-abstract relationship', primary_key=True, serialize=False)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speculum_mundi_data.timeline')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineToTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for timeline-timeline relationship', primary_key=True, serialize=False)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause', to='speculum_mundi_data.timeline')),
            ],
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='source',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='topic',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for discussion', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.AddField(
            model_name='timelinetotimeline',
            name='discussions',
            field=models.ManyToManyField(to='speculum_mundi_data.discussion'),
        ),
        migrations.AddField(
            model_name='timelinetotimeline',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='speculum_mundi_data.timeline'),
        ),
        migrations.AddField(
            model_name='timelinetoabstract',
            name='discussions',
            field=models.ManyToManyField(to='speculum_mundi_data.discussion'),
        ),
        migrations.AddField(
            model_name='timelinetoabstract',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speculum_mundi_data.abstract'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='discussions',
            field=models.ManyToManyField(to='speculum_mundi_data.discussion'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='discussions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speculum_mundi_data.discussion'),
        ),
        migrations.AddField(
            model_name='location',
            name='discussions',
            field=models.ManyToManyField(to='speculum_mundi_data.discussion'),
        ),
        migrations.AddField(
            model_name='location',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speculum_mundi_data.timeline'),
        ),
        migrations.AddField(
            model_name='abstracttotimeline',
            name='discussions',
            field=models.ManyToManyField(to='speculum_mundi_data.discussion'),
        ),
        migrations.AddField(
            model_name='abstracttotimeline',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speculum_mundi_data.timeline'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='discussions',
            field=models.ManyToManyField(to='speculum_mundi_data.discussion'),
        ),
    ]
