# Generated by Django 4.0.3 on 2022-04-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speculum_mundi_data', '0003_abstract_abstracttotimeline_location_opinion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
