# Generated by Django 4.0.3 on 2022-04-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speculum_mundi_data', '0004_alter_discussion_timestamp_alter_opinion_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='discussions',
            field=models.ManyToManyField(blank=True, to='speculum_mundi_data.discussion'),
        ),
        migrations.AlterField(
            model_name='abstracttotimeline',
            name='discussions',
            field=models.ManyToManyField(blank=True, to='speculum_mundi_data.discussion'),
        ),
        migrations.AlterField(
            model_name='location',
            name='discussions',
            field=models.ManyToManyField(blank=True, to='speculum_mundi_data.discussion'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='discussions',
            field=models.ManyToManyField(blank=True, to='speculum_mundi_data.discussion'),
        ),
        migrations.AlterField(
            model_name='timelinetoabstract',
            name='discussions',
            field=models.ManyToManyField(blank=True, to='speculum_mundi_data.discussion'),
        ),
        migrations.AlterField(
            model_name='timelinetotimeline',
            name='discussions',
            field=models.ManyToManyField(blank=True, to='speculum_mundi_data.discussion'),
        ),
    ]
