# Generated by Django 4.0.3 on 2022-04-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speculum_mundi_data', '0005_alter_abstract_discussions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='upvote',
            field=models.IntegerField(null=True),
        ),
    ]
