# Generated by Django 4.0.3 on 2022-04-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speculum_mundi_data', '0007_alter_opinion_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='upvote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
