# Generated by Django 4.0.3 on 2022-04-10 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailedEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.entry')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('source', models.URLField(blank=True)),
            ],
            bases=('data.entry',),
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('detailedentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.detailedentry')),
                ('type', models.CharField(choices=[('LOCATION', 'Location'), ('EVENT', 'Event'), ('PERSON', 'Person'), ('IDEA', 'Idea'), ('ORGANIZATION', 'Organization'), ('ARTIFACT', 'Artifact'), ('MANUSCRIPT', 'Manuscript')], default='EVENT', max_length=30)),
            ],
            bases=('data.detailedentry',),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.entry')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_discussions', to='contenttypes.contenttype')),
            ],
            bases=('data.entry',),
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('detailedentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.detailedentry')),
                ('context', models.ManyToManyField(blank=True, to='data.abstract')),
            ],
            bases=('data.detailedentry',),
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('detailedentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.detailedentry')),
                ('upvotes', models.IntegerField(blank=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='data.discussion')),
            ],
            bases=('data.detailedentry',),
        ),
        migrations.CreateModel(
            name='LocationShift',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.entry')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='data.abstract')),
                ('destination_timeline_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination_node', to='data.timelineevent')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='data.abstract')),
                ('origin_timeline_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origin_node', to='data.timelineevent')),
            ],
            bases=('data.entry',),
        ),
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('geography', models.TextField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.abstract')),
                ('timeline_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.timelineevent')),
            ],
        ),
        migrations.CreateModel(
            name='CauseEffect',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.entry')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause', to='data.timelineevent')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect', to='data.timelineevent')),
            ],
            bases=('data.entry',),
        ),
    ]
