# Generated by Django 4.0.3 on 2022-05-12 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersave',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('detailedentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.detailedentry')),
                ('type', models.CharField(choices=[('LOCATION', 'Location'), ('EVENT', 'Event'), ('PERSON', 'Person'), ('IDEA', 'Idea'), ('COUNTRY', 'Country'), ('ORGANIZATION', 'Organization'), ('ARTIFACT', 'Artifact'), ('MANUSCRIPT', 'Manuscript')], default='EVENT', max_length=30)),
            ],
            bases=('data.detailedentry',),
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('detailedentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.detailedentry')),
                ('upvotes', models.IntegerField(blank=True)),
            ],
            bases=('data.detailedentry',),
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('detailedentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.detailedentry')),
                ('event_year', models.IntegerField(blank=True, null=True)),
                ('event_month', models.IntegerField(blank=True, null=True)),
                ('event_date', models.IntegerField(blank=True, null=True)),
                ('context', models.ManyToManyField(blank=True, to='data.abstract')),
            ],
            bases=('data.detailedentry',),
        ),
        migrations.AddField(
            model_name='usersave',
            name='temp_cause_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.causeeffect'),
        ),
        migrations.AddField(
            model_name='usersave',
            name='temp_discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.discussion'),
        ),
        migrations.AddField(
            model_name='usersave',
            name='temp_location_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.locationshift'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='cause_effect_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_effect_context', to='data.causeeffect'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='location_shift_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_shift_context', to='data.locationshift'),
        ),
        migrations.AddField(
            model_name='usersave',
            name='saved_abstracts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pulled', to='data.abstract'),
        ),
        migrations.AddField(
            model_name='usersave',
            name='temp_abstracts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_added', to='data.abstract'),
        ),
        migrations.AddField(
            model_name='usersave',
            name='temp_opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.opinion'),
        ),
        migrations.AddField(
            model_name='usersave',
            name='temp_timeline_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.timelineevent'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='data.discussion'),
        ),
        migrations.AddField(
            model_name='locationshift',
            name='destination_timeline_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_node', to='data.timelineevent'),
        ),
        migrations.AddField(
            model_name='locationshift',
            name='origin_timeline_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_node', to='data.timelineevent'),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.abstract'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='abstract_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abstract_context', to='data.abstract'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='timeline_event_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_event_context', to='data.timelineevent'),
        ),
        migrations.AddField(
            model_name='causeeffect',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause', to='data.timelineevent'),
        ),
        migrations.AddField(
            model_name='causeeffect',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect', to='data.timelineevent'),
        ),
    ]
