# Generated by Django 4.0.3 on 2022-04-11 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationshift',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='locationshift',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='locationinfo',
            name='timeline_event',
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='timeline_event',
            field=models.ManyToManyField(blank=True, to='data.timelineevent'),
        ),
        migrations.AlterField(
            model_name='locationshift',
            name='destination_timeline_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_node', to='data.timelineevent'),
        ),
        migrations.AlterField(
            model_name='locationshift',
            name='origin_timeline_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_node', to='data.timelineevent'),
        ),
    ]
