# Generated by Django 4.0.3 on 2022-04-12 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_locationshift_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='object_id',
        ),
        migrations.AddField(
            model_name='discussion',
            name='abstract_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abstract_context', to='data.abstract'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='cause_effect_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_effect_context', to='data.causeeffect'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='location_shift_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_shift_context', to='data.locationshift'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='timeline_event_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_event_context', to='data.timelineevent'),
        ),
    ]
