# Generated by Django 4.0.3 on 2022-04-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_discussion_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationinfo',
            name='timeline_event',
        ),
    ]
