# Generated by Django 4.0.3 on 2022-04-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_abstract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='event_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='event_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='event_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
