# Generated by Django 4.0.3 on 2022-06-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_detailedentry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_abstract', to='data.abstract'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='context',
            field=models.ManyToManyField(blank=True, related_name='all_abstracts', to='data.abstract'),
        ),
    ]
