# Generated by Django 4.0.3 on 2022-06-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_timelineevent_location_alter_timelineevent_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='shared',
            field=models.BooleanField(default=True),
        ),
    ]
