# Generated by Django 4.0.3 on 2022-05-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_detailedentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedentry',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
