# Generated by Django 4.0.6 on 2023-03-15 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0010_opinion_stance_alter_causeeffect_cause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='shared',
        ),
        migrations.AddField(
            model_name='opinion',
            name='quoted',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.entry')),
                ('votes_min', models.IntegerField(blank=True, null=True)),
                ('votes_max', models.IntegerField(blank=True, null=True)),
                ('quotes_min', models.IntegerField(blank=True, null=True)),
                ('quotes_max', models.IntegerField(blank=True, null=True)),
                ('diagram_filter', models.CharField(choices=[('ALL_TRUE', 'All true'), ('ALL_FALSE', 'All false'), ('MORE_OPINIONS', 'More opinions'), ('MOST_UPVOTED_OPINION', 'Most upvoted opinion'), ('MOST_QUOTED_OPINION', 'Most quoted opinion')], max_length=30)),
                ('abstracts', models.ManyToManyField(blank=True, null=True, related_name='associated_diagrams', to='data.abstract')),
                ('specified', models.ManyToManyField(blank=True, null=True, related_name='specifying_opinion', to='data.opinion')),
            ],
            bases=('data.entry',),
        ),
    ]
